In [16]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import os
import sys

print('=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=')
print('Python version ' + sys.version)
print('Numpy version ' + np.version.version)
print('Pandas version ' + pd.__version__)
print('MatplotLib version ' + matplotlib.__version__)
print('=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=')

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Python version 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Numpy version 1.16.2
Pandas version 0.24.2
MatplotLib version 3.0.3
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

In [91]:
# Hardcoded filepath for testing and dev purposes
file = r'C:\Users\Czarified\Downloads\latest.log'

# Initialize the data array
data = pd.DataFrame(dtype=float)

temp = []
with open(file) as f:
    for line in f.readlines():
        # If it's a line with eco stat data (they are all flagged)
        if 'ECOSTATS' in line:
            # Cut off the preceding bits we dont care about
            cache = line.split(sep='ECOSTATS: ,')[1]
            
            
            temp.append(cache.split(sep=','))
            
data = data.append(temp)
data.columns=['Time', 'Team',
              'Food_Prod', 'Lumber_Prod', 'Stone_Prod', 'Iron_Prod', 'Gold_Prod', 'Diamond_Prod', 'Emerald_Prod',
              'Food', 'Lumber', 'Stone', 'Iron', 'Gold', 'Diamonds', 'Emeralds'
             ]


data.Time = pd.to_datetime(data.Time)
data.Team = data.Team.astype(str)
data.Food = data.Food.astype(int)
print(data.dtypes)

Time            object
Team            object
Food_Prod       object
Lumber_Prod     object
Stone_Prod      object
Iron_Prod       object
Gold_Prod       object
Diamond_Prod    object
Emerald_Prod    object
Food            object
Lumber          object
Stone           object
Iron            object
Gold            object
Diamonds        object
Emeralds        object
dtype: object

In [65]:
red = data.loc[data.Team == 'red'].copy()

In [82]:
red.set_index(red.Time, inplace=True)

ValueError: could not convert string to float: '2019/11/18 20:51:20'

In [68]:
red.tail()

,Time,Team,Food_Prod,Lumber_Prod,Stone_Prod,Iron_Prod,Gold_Prod,Diamond_Prod,Emerald_Prod,Food,Lumber,Stone,Iron,Gold,Diamonds,Emeralds
1201,2019/11/18 21:42:18,red,13,13,9,8,5,1,0,1364,1020,809,418,332,249,0\n
1205,2019/11/18 21:42:28,red,13,13,9,8,5,1,0,1377,1033,818,426,337,250,0\n
1209,2019/11/18 21:42:38,red,13,13,9,8,5,1,0,1390,1046,827,434,342,251,0\n
1213,2019/11/18 21:42:48,red,13,13,9,8,5,1,0,1403,1059,836,442,347,252,0\n
1217,2019/11/18 21:42:58,red,13,13,9,8,5,1,0,1416,1072,845,450,352,253,0\n